### PR TITLE
Leaderboard

### PR DESCRIPTION
**Pull request by boo-shehab**
# Hi Reviewer 👋 
 in this branch, I create My own design using CSS

### CODE REVIEW

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @boo-shehab, 

# Required Changes ♻️

Good job so far!
You have done it well 👏🏽 👏🏽 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Correct Git flow ✔️ 
- Descriptive PR ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please 🙏🏽 add the instructions to use your app in the **`GETTING STARTED`** section on your README file 👇🏽 

**HINT**
1. Clone the repo `git@github.com:boo-shehab/Leaderboard.git`
2. Change to the corresponding branch `git checkout leaderboard`
3. Run `npm i` in your terminal.
4. Run `npm start` in your terminal.
5. Enjoy my app.

- [ ] **[OPTIONAL]** ⚠️ Kindly review the announcements on the Slack channel Microverse has updated the [README template](https://github.com/microverseinc/readme-template) they recommend using it when documenting our projects. It’s crucial to have a solid README file because this will demonstrate your professionalism and make your project more accessible to other developers (and future employers).
We would like to encourage you to:
1. Update all of your current project READMEs with elements of this template
2. Add at least 1 future feature you could develop (and potentially even would develop if you’re still in the job searching module)
**IT WILL BE MANDATORY TO USE THE NEW README TEMPLATE ON NEXT WEEK.**
Happy coding! 💻 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by boo-shehab** [comment]
Hi @franclobo  thanks for your hard work I made the changes in the readme file and I just want to know if it's good now to ask for another review

**Comment by franclobo** [comment]
Hi, @boo-shehab yes, you can submit it for a new re-review. Please 🙏🏽 take in mind on next week it will be mandatory to use the new [README template](https://github.com/microverseinc/readme-template) in your repository.

**Comment by boo-shehab** [comment]
@franclobo  Thanks for your help and your, yes I'll use the new readme.md for all upcoming repo thanks again

**Review by zainsadaqat — APPROVED** [review]
# Pull Request Approved ✅ 🎊 🎉 
## Hello @boo-shehab  👋 
### [OPTIONAL]
- [ ] Kindly correct the branch name spellings from `div` to `dev` or `development` 😃 

### Your project is complete!  There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
